M48
; DRILL file KiCad 10.0.0 date 2026-04-15T11:24:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-15T11:24:36-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X151.0Y-108.0
T2
X121.3Y-117.027
X134.0Y-117.027
T3
X150.643Y-114.534
X150.643Y-117.074
M30
